apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: texture-pack-downloader
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  rules:
  - host: packs.els.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: texture-pack-downloader
            port:
              number: 80
